[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
providers = ["node"]

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_18"]

[build.nixpacksPlan.phases.install]
cmds = ["npm ci"]

[build.nixpacksPlan.phases.build]
cmds = ["npm run build"]

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
